[package]
name = "choco"
version.workspace = true
edition.workspace = true

[[bin]]
name = "choco"
path = "src/main.rs"

[dependencies]
chocofactory-core = { path = "../chocofactory-core" }
chrono = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
